# Follow format: <Category>; .<extension>, .<extension>, ...
# Supported categories are Documents, Images, Videos, Audio, Archives, Code, Executables, Fonts, Shortcuts, System Library

Documents; .geowrite, .qdw
Videos; .roq